# Generated by Django 4.0 on 2024-05-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover_and_more'),
        ('recipes', '0002_auto_20211130_0929'),
    ]

    operations = [
    ]
